Fixed https://github.com/Ashald/EnvFile/issues/27
Ashald/EnvFile pull request #28
Opened 2017-03-10 17:05 UTC by yoanthiebault

This commit aims to fix https://github.com/Ashald/EnvFile/issues/27. The idea is to use updateJavaParameters instead of patchCommandLine in IdeaRunConfigurationExtension

2017-03-11 21:13 UTC, Ashald commented
Thanks for the contribution! I looked over the code and it looks good to me generally, although I would prefer to change one thing in terms of the interface.

2017-03-11 21:16 UTC, ashald requested changes
Thanks for the contribution! I looked over the code and it looks good to me generally, although I would prefer to change one thing in terms of the interface.

2017-03-11 21:16 UTC, Ashald commented on project/platform/src/net/ashald/envfile/platform/ui/EnvFileConfigurationEditor.java
> +    public static void patchJavaParameters(@NotNull RunConfigurationBase configuration, JavaParameters params, RunnerSettings runnerSettings) throws ExecutionException {
The initial design aim for this class was to keep it as generic as possible and use it in concrete implementations. From this perspective rather then keeping methods like `patchCommandLine`  and `patchJavaParameters` I'd rather go with single method `patchEnvironmentVariables` (as you essentially did) and move 1-liners from `patchCommandLine`/`patchJavaParameters` to concrete implementations.

2017-03-12 11:05 UTC, yoanthiebault commented on project/platform/src/net/ashald/envfile/platform/ui/EnvFileConfigurationEditor.java
> +    public static void patchJavaParameters(@NotNull RunConfigurationBase configuration, JavaParameters params, RunnerSettings runnerSettings) throws ExecutionException {
Done !
Just for information, I couldn't test it with RubyMine and PyCharm but it should work :)

2017-03-14 00:48 UTC, ashald approved these changes
Looks good!

2017-03-14 00:49 UTC, merged